#!/usr/bin/env bash
# counts to 100 and fizzbuzzes multiples of 3 and 5
for i in {1..100}; do
    if ((i % 3 == 0 && i % 5 == 0)); then
	echo "FizzBuzz"
    elif ((i % 3 == 0)); then
	echo "Fizz"
    elif ((i % 5 == 0)); then
	echo "Buzz"
    else
	echo $i
    fi
done
#alt1: if [[ $(( i % 3 )) -eq 0 && $(( i % 5 )) -eq 0 ]];
#alt2: if [ $(( i % 3 )) -eq 0 ] && [ $(( i % 5 )) -eq 0 ];
